# Generated by Django 4.0.5 on 2022-07-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_identity_post_author_identity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_identity',
            new_name='author_ID',
        ),
    ]
