# Generated by Django 4.0.5 on 2022-07-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_author_identity_post_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_ID',
            new_name='author_identity',
        ),
    ]
